version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
    groups:
      javascript-action:
        patterns:
          - "*"

  - package-ecosystem: pip
    directory: "/.github/requirements"
    schedule:
      interval: weekly
    groups:
      python-lint-tools:
        patterns:
          - "*"
