name: Lint

permissions:
  contents: read

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  merge_group:
    types: [checks_requested]
  push:
    branches:
      - main

concurrency:
  group: lint-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Setup Python
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: "3.14"

      - name: Install Pre-Commit
        run: python -m pip install pre-commit==4.6.0

      - name: Run Pre-Commits
        run: pre-commit run --all-files --hook-stage pre-push
