name: Release Please Runner

on:
  workflow_call:
    inputs:
      target-branch:
        required: false
        type: string
        default: main
      skip-github-release:
        required: false
        type: boolean
        default: false
      skip-github-pull-request:
        required: false
        type: boolean
        default: false
    secrets:
      token:
        required: true

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Run Release Please
        uses: googleapis/release-please-action@16a9c90856f42705d54a6fda1823352bdc62cf38 # v4.4.0
        with:
          token: ${{ secrets.token }}
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json
          target-branch: ${{ inputs.target-branch }}
          skip-github-release: ${{ inputs.skip-github-release }}
          skip-github-pull-request: ${{ inputs.skip-github-pull-request }}
