name: Release Test

on:
  pull_request:
    branches:
      - main
    paths:
      - release-please-config.json
      - .release-please-manifest.json
  workflow_dispatch:

concurrency:
  group: release-test-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: read

jobs:
  release-please-test:
    uses: ./.github/workflows/release-please-runner.yml
    with:
      target-branch: main
      skip-github-release: true
      skip-github-pull-request: true
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
